In [1]:
%load_ext autoreload
%autoreload 2

# `Logit` on Orders - Logistic Regression (~1h)

## Select features

🎯 Haydi `wait_time` ve `delay_vs_expected` değişkenlerinin çok `iyi/kötü review`lar üzerindeki etkisini inceleyelim.

👉 `orders` training_set’imizi kullanarak iki adet `multivariate logistic regression` çalıştıracağız:
- `logit_one` → `dim_is_one_star` tahmini için  
- `logit_five` → `dim_is_five_star` tahmini için.

In [2]:
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

👉 Dataset’inizi import edin:

In [4]:
from olist.order import Order
orders = Order().get_training_data(with_distance_seller_customer=False)

👉 Kullanmak istediğiniz feature’ları bir listede seçin:

⚠️ Data leakage yaratmadığınızdan emin olun (yani target’tan türetilmiş feature’ları seçmeyin)

💡 `wait_time` ve `delay_vs_expected` değişkenlerinin etkisini anlayabilmek için diğer feature’ların etkisini kontrol etmemiz gerekir, bu yüzden listenize ilgili olabilecek tüm feature’ları dahil edin.

In [10]:
features = [
    "wait_time",
    "delay_vs_expected",
    "expected_wait_time",
    "price",
    "freight_value",
    "number_of_items",
    "number_of_sellers"
]

In [11]:
orders.columns

Index(['order_id', 'wait_time', 'expected_wait_time', 'delay_vs_expected',
       'order_status', 'dim_is_five_star', 'dim_is_one_star', 'review_score',
       'number_of_items', 'number_of_sellers', 'price', 'freight_value'],
      dtype='object')

In [9]:
[c for c in orders.columns if "product" in c.lower()]

[]

In [12]:
X = orders[features].copy()
X.head()

,wait_time,delay_vs_expected,expected_wait_time,price,freight_value,number_of_items,number_of_sellers
0,8.436574,0.0,15.544063,29.99,8.72,1,1
1,13.782037,0.0,19.137766,118.70,22.76,1,1
2,9.394213,0.0,26.639711,159.90,19.22,1,1
3,13.208750,0.0,26.188819,45.00,27.20,1,1
4,2.873877,0.0,12.112049,19.90,8.72,1,1

🕵🏻 Feature’larınızın `multicollinearity` durumunu `VIF index` kullanarak kontrol edin.

* Çok yüksek olmamalıdır (tercihen < 10), böylece partial regression coefficient’larına ve ilgili `p-values` değerlerine güvenebiliriz.
* Verinizi standardize etmeyi unutmayın!
    * Bir `VIF Analysis`, bir feature’ın diğer feature’lara karşı regresyonunu yaparak hesaplanır...
    * Bu yüzden herhangi bir linear regression çalıştırmadan önce feature’ların `scale etkisini kaldırmak` ve eşit öneme sahip olmalarını sağlamak istersiniz!
    
    
📚 <a href="https://www.statisticshowto.com/variance-inflation-factor/">Statistics How To - Variance Inflation Factor</a>

📚  <a href="https://online.stat.psu.edu/stat462/node/180/">PennState - Detecting Multicollinearity Using Variance Inflation Factors</a>

⚖️ Standardize etme:

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns,
    index=X.index
)

X_scaled.head()

,wait_time,delay_vs_expected,expected_wait_time,price,freight_value,number_of_items,number_of_sellers
0,-0.432086,-0.16212,-0.935934,-0.514188,-0.653046,-0.264658,-0.112588
1,0.133145,-0.16212,-0.525645,-0.086552,0.000102,-0.264658,-0.112588
2,-0.330825,-0.16212,0.330841,0.112057,-0.164581,-0.264658,-0.112588
3,0.072525,-0.16212,0.279364,-0.441830,0.206653,-0.264658,-0.112588
4,-1.020287,-0.16212,-1.327762,-0.562827,-0.653046,-0.264658,-0.112588

👉 Olası multicollinearity durumlarını analiz etmek için VIF Analysis’inizi çalıştırın:

In [14]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_df = pd.DataFrame()
vif_df["feature"] = X_scaled.columns
vif_df["VIF"] = [
    variance_inflation_factor(X_scaled.values, i)
    for i in range(X_scaled.shape[1])
]

vif_df

              feature       VIF
0           wait_time  2.832725
1   delay_vs_expected  2.379695
2  expected_wait_time  1.443633
3               price  1.204880
4       freight_value  1.577027
5     number_of_items  1.348236
6   number_of_sellers  1.095442

## Logistic Regressions

👉 İki adet `Logistic Regression` modeli fit edin:
- `logit_one` → `dim_is_one_star` tahmini için
- `logit_five` → `dim_is_five_star` tahmini için.

`Logit 1️⃣`

In [15]:
import statsmodels.api as sm

y_one = orders["dim_is_one_star"]

X_logit = sm.add_constant(X_scaled)

logit_one = sm.Logit(y_one, X_logit)
result_one = logit_one.fit()

result_one.summary()

Optimization terminated successfully.
         Current function value: 0.273079
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:        dim_is_one_star   No. Observations:                96353
Model:                          Logit   Df Residuals:                    96345
Method:                           MLE   Df Model:                            7
Date:                Sun, 04 Jan 2026   Pseudo R-squ.:                  0.1461
Time:                        14:28:22   Log-Likelihood:                -26312.
converged:                       True   LL-Null:                       -30814.
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                 -2.4824      0.013   -189.580      0.000      -2.508      -2.457
wait_time              0.7956      0.019     41.530      0.000       0.758       0.833
delay_vs_expected      0.1573      0.020      7.794      0.000       0.118       0.197
expected_wait_time    -0.2484      0.016    -15.450      0.000      -0.280      -0.217
price                  0.0579      0.011      5.127      0.000       0.036       0.080
freight_value         -0.0422      0.013     -3.193      0.001      -0.068      -0.016
number_of_items        0.2645      0.011     24.977      0.000       0.244       0.285
number_of_sellers      0.1867      0.008     23.639      0.000       0.171       0.202
======================================================================================
"""

`Logit 5️⃣`

In [16]:
y_five = orders["dim_is_five_star"]

logit_five = sm.Logit(y_five, X_logit)
result_five = logit_five.fit()

result_five.summary()

Optimization terminated successfully.
         Current function value: 0.636930
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:       dim_is_five_star   No. Observations:                96353
Model:                          Logit   Df Residuals:                    96345
Method:                           MLE   Df Model:                            7
Date:                Sun, 04 Jan 2026   Pseudo R-squ.:                 0.05787
Time:                        14:28:30   Log-Likelihood:                -61370.
converged:                       True   LL-Null:                       -65140.
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.3427      0.007     48.102      0.000       0.329       0.357
wait_time             -0.5389      0.012    -44.095      0.000      -0.563      -0.515
delay_vs_expected     -0.3818      0.024    -16.046      0.000      -0.428      -0.335
expected_wait_time     0.0943      0.008     11.206      0.000       0.078       0.111
price                  0.0167      0.008      2.201      0.028       0.002       0.032
freight_value          0.0180      0.009      2.071      0.038       0.001       0.035
number_of_items       -0.1447      0.008    -17.454      0.000      -0.161      -0.128
number_of_sellers     -0.1450      0.008    -18.550      0.000      -0.160      -0.130
======================================================================================
"""

💡 Şimdi bu iki logistic regression’ın sonuçlarını analiz etme zamanı:

- Partial coefficient’ları kendi kelimelerinizle yorumlayın.
- `p-values` kullanarak istatistiksel anlamlılıklarını kontrol edin.
- Coefficient önemleri açısından `logit_one` ve `logit_five` arasında herhangi bir fark görüyor musunuz?

In [19]:
# Aşağıdaki cümlelerden doğru olanları aşağıdaki listeye kaydedin.

a = "delay_vs_expected influences five_star ratings even more than one_star ratings"
b = "wait_time influences five_star ratings even more than one_star"

your_answer = [a]

🧪 __Kodunu Test Et__

In [20]:
from nbresult import ChallengeResult

result = ChallengeResult('logit',
    answers = your_answer
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/selen/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/selen/olist-work/challenges/data-logit/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 1 item

test_logit.py::TestLogit::test_question PASSED                           [100%]

============================== 1 passed in 0.01s ===============================


💯 You can commit your code:

git add tests/logit.pickle

git commit -m 'Completed logit step'

git push origin master

<details>
    <summary>- <i>Açıklamalar ve ileri seviye kavramlar</i> -</summary>


> _Diğer tüm şeyler sabitken, `delay factor`, 1-yıldız review alma ihtimalini etkilemesinden bile daha fazla, 5-yıldızdan mahrum kalma ihtimalini artırma eğilimindedir. Muhtemelen bunun sebebi, 1-yıldız review’ların bizzat çok kötü ürünleri hedeflemesi, kötü teslimatları değil._

❗️ Ancak tamamen titiz olmak için, **iki farklı modelin coefficient’larını karşılaştırırken daha dikkatli olmamız gerekir**, çünkü **benzer popülasyonlara dayanmayabilirler**!
    Burada 2 alt popülasyonumuz var: (1-yıldız verenler ve 5-yıldız verenler) ve bunlar doğaları gereği farklı davranış kalıpları sergileyebilirler. 5-yıldız vermeye daha meyilli “mutlu insanlar”ın, “gecikme” veya “fiyat” söz konusu olduğunda, 1-yıldızı “Lucky-Luke gibi ateşleyen” “huysuz insanlara” göre daha az hassas olmaları gayet mümkün...

</details>

🏁 Tebrikler!

💾 `logit.ipynb` notebook’unuzu commit ve push etmeyi unutmayın!